### ISSUE TITLE
improve granularity of listeners

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cabal-client#23]
khubo and nick, and myself while starting to patch [cabal-irc](https://github.com/cabal-club/cabal-irc/tree/cabal-client-upgrade), have felt a need to have more granular listeners than `on("update")`

as an example: [this method](https://github.com/cabal-club/cabal-desktop/blob/b67019999d9e96144c57504201293e50b55f4ff9/app/actions.js#L388-L409), from cabal-desktop, would be split up into several listeners

i haven't had a sit down to think properly about which ones yet but maybe:
* `"new message", channel`
* `"join/leave channel", channel` does this need to be disambiguated? one event type for the person who is running the client; the other event type for when other peers join or leave specific channels?
* `"nick change", {userkey, newnick}`
* `"topic", channel, topic`, maybe just a channel state changed event? that includes new people joining/leaving and topics changing.
* `"initialization"`, this fires basically when all data is available after first starting up a client. it is only triggered once

it could also be interesting to include a _delta_, the change in state that occurred in the current update, that can optionally be used (that way client implementations don't necessarily need to be in a reactive framework like [react](https://reactjs.org/) or [vue](https://vuejs.org/). introducing a delta could however cause weird errors stemming from out of order updates.

@khubo @nikolaiwarner chime in on your recent impressions and thoughts when developing cabal-desktop so excellently these past 2-3 weeks. which specific cases were aching for more granular listeners?

**Comment by khubo** [comment]
"messages"  tops the list from `cabal-desktop` perspective. Since whenever a new message comes we have to update new message count, show a notification badge near the cabal etc. We are doing that for all sort of updates now. 
  Also, peers gets connected/disconnected frequently, which also triggers too many updates.

**Comment by nikolaiwarner** [comment]
@cblgh those are all great
@khubo yeah an event for peer changes would be a real good one

also how about:
- "new channel"

@cblgh should we make individual issues for each one so we can split up the effort?

**Comment by cblgh** [comment]
@nikolaiwarner if you want to, otherwise i figure just implementing them all in one go makes more sense (at least as regards cabal-client) :~

**Comment by nikolaiwarner** [comment]
✊

**Comment by cblgh** [comment]
shower thought: each invocation of `this._emitUpdate()` can be changed to `this.emitUpdate("<type>", {<payload>})`

and redefining the `emitUpdate` function as
```js
  _emitUpdate(type, payload) {
    if (!this.disableGlobalUpdate) this.emit('update', this)
    this.emit(type, payload)
  }
```

i still think there's value in having the single `update` emitter, as it simplifies anyone's first client.
